language: node_js

node_js:
  - 9

cache:
  directories:
    - node_modules

branches:
  only:
  - master

addons:
  ssh_known_hosts: deplink.org

stages:
  - deploy
  - validate

jobs:
  include:
    - stage: deploy
      script:
        - npm install
        - npm run prod
        - chmod +x deploy.sh
        - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./deploy.sh; fi
    - stage: validate
      script:
        - chmod +x tests/crawler.sh
        - tests/crawler.sh https://deplink.org