language: node_js

node_js:
  - "node"

branches:
  only:
  - master

addons:
  ssh_known_hosts: deplink.org

install:
  - npm install

script:
  - npm run prod
  - chmod +x deploy.sh
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./deploy.sh; fi
