language: node_js

node_js:
  - "node"

branches:
  only:
  - master

addons:
  ssh_known_hosts: deplink.org

install:
  - npm install

script:
  - npm run prod

  # Register Travis CI key
  - eval "$(ssh-agent -s)"
  - ssh-add - <<< "${$TRAVIS_KEY}"

  # Upload "build" directory to server
  - scp -r build/* travis@deplink.org:~/
