language: node_js

node_js:
  - "node"

branches:
  only:
  - master

addons:
  ssh_known_hosts: deplink.org

install:
  - npm install

script:
  - npm run prod

  # Register Travis CI key
  - eval "$(ssh-agent -s)"
  - mkdir -p ~/.ssh && chmod 700 ~/.ssh
  - echo "${TRAVIS_KEY64}" > ~/.ssh/travis_rsa64
  - base64 --decode ~/travis_rsa64 > ~/.ssh/travis_rsa
  - chmod 600 ~/.ssh/travis_rsa
  - ssh-add ~/travis_rsa

  # Upload "build" directory to server
  - scp -r build/* travis@deplink.org:~/
