language: node_js

node_js:
  - "node"

branches:
  only:
  - master

addons:
  ssh_known_hosts: deplink.org

install:
  - npm install

script:
  - npm run prod

deploy:
  provider: script
  skip_cleanup: true
  script: deploy.sh
  on:
    branch: master
